CREATE TABLE IF NOT EXISTS public.groups
(
    group_id INT,
    group_name character varying,
    PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    course_id INT,
    course_name character varying,
    course_description character varying,
    PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.students
(
    student_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 200),
    group_id INT,
    first_name character varying,
    last_name character varying
);

CREATE TABLE students_courses
( 
   student_id INT REFERENCES students ON DELETE CASCADE,
   course_id INT REFERENCES courses ON DELETE CASCADE,
   PRIMARY KEY (student_id, course_id)
);
