CREATE TABLE IF NOT EXISTS public.students
(
    student_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 200),
    group_id integer,
    first_name character varying,
    last_name character varying
);
